### ISSUE TITLE
Hide useless informations in list command

### ISSUE THREAD

**Issue by steevanb** [Huttopia/console-bundle#13]
When no command to execute (`bin/console`), an help is showned (everything before `cache:clear`):
https://zupimages.net/up/20/12/9uoe.png

It's usefull when we start to use symfony/console, but not really when we know how to use it.

We can hide all this informations by default, and show it only when verbose (`-v`, `-vv` or `-vvv`)?
Or we can configure if we want to show it by default / only when verbose?

**Comment by ZeMarine** [comment]
A configuration is actually a good idea. Show it only when verbose is a nonsense, because the beginners won't be aware of theses shortcuts :).
